# Generated by Django 2.2.7 on 2019-11-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CIMIT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='web',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='zipcode',
        ),
    ]
