# Generated by Django 2.2.7 on 2019-11-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CIMIT', '0002_auto_20191120_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='address',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='email_address',
        ),
        migrations.AddField(
            model_name='venue',
            name='password',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
