# Generated by Django 2.2.7 on 2019-11-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CIMIT', '0003_auto_20191120_0355'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='venue',
            table='Venue',
        ),
    ]
