# Generated by Django 2.2.7 on 2019-11-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CIMIT', '0004_auto_20191120_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='Emailid',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='venue',
            name='confirmpassword',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
