# Generated by Django 2.2.6 on 2019-11-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_auto_20191107_0128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Employee',
        ),
    ]
